Repository andrew-fennell/CogNative, pull requests merged in 2022-03, with the labels that each got.

#23 Added structure to GitHub files and installation procedures
  .gitignore
  CogNative/backend/README.md
  CogNative/hardware/README.md
  CogNative/models/README.md
  README.md
  docs/README.md
  requirements.txt
Labels: documentation, management

#26 Aref translation api
  CogNative/backend/translation/README
  CogNative/backend/translation/translation.py
  requirements.txt
Labels: software

#27 Added Speech-to-Text Class
  CogNative/backend/speech-to-text/README.md
  CogNative/backend/speech-to-text/STT.py
  requirements.txt
Labels: software

#32 Installation guide
  README.md
Labels: documentation

#33 Update README.md
  README.md
Labels: documentation

#35 Updated numpy and ipython (security patches)
  requirements.txt
Labels: ML/AI, dependencies

#36 Remove pretrained models
  CogNative/models/Real-Time-Voice-Cloning/saved_models/default/README.md
  CogNative/models/Real-Time-Voice-Cloning/saved_models/default/encoder.pt
  CogNative/models/Real-Time-Voice-Cloning/saved_models/default/synthesizer.pt
  CogNative/models/Real-Time-Voice-Cloning/saved_models/default/vocoder.pt
Labels: documentation, ML/AI
