Repository andrew-fennell/CogNative, pull requests merged in 2022-04, with the labels that each got.

#48 Noise reduction postprocessing preliminary setup
  CogNative/models/Real-Time-Voice-Cloning/main.py
  README.md
  requirements.txt
Labels: documentation, enhancement

#49 Improved issue with noise reduction volume dips.
  CogNative/models/Real-Time-Voice-Cloning/main.py
Labels: enhancement

#55 Fixed printing bug; Fixed WindowsPath write bug
  .gitignore
  CogNative/main.py
  CogNative/models/RTVC/RTVC.py
  CogNative/models/RTVC/utils/printing.py
Labels: bug, critical

#59 Cross-language vocal synthesis
  CogNative/main.py
  CogNative/models/RTVC/RTVC.py
Labels: ML/AI

#58 Added embedding checkpoints
  .gitignore
  CogNative/examples/saved_embeds/examples;BillMaher22.wav.ckpt
  CogNative/examples/saved_embeds/examples;DavidHowell15.wav.ckpt
  CogNative/examples/saved_embeds/examples;TCOC40.wav.ckpt
  CogNative/main.py
  CogNative/models/RTVC/RTVC.py
Labels: enhancement, ML/AI

#61 UI
  CogNative/testUI/UI.py
  requirements.txt
Labels: frontend

#66 Switched from SpeechRecognition to Google Cloud Speech
  .github/workflows/python-app.yml
  .gitignore
  CogNative/backend/README.md
  CogNative/backend/backend.py
  CogNative/backend/modules/STT.py
  README.md
  credentials.json.template
  docs/README.md
  requirements.txt
  tests/backend/modules/test_STT.py
Labels: enhancement, software

#67 Integrates STT and translation into main.py
  CogNative/backend/backend.py
  CogNative/backend/modules/STT.py
  CogNative/main.py
  README.md
Labels: enhancement, software

#69 Created hardware doc
  CogNative/hardware/README.md
  docs/README.md
Labels: documentation, hardware

#70 Fixed paths in main.py and RTVC
  CogNative/main.py
  CogNative/models/RTVC/RTVC.py
Labels: bug, ML/AI

#72 Austin- command line arguments support
  CogNative/main.py
  cmdTestAudio.bat
  cmdTestText.bat
Labels: enhancement, frontend

#68 Added skeleton to UI
  CogNative/models/__init__.py
  CogNative/testUI/UI.py
  CogNative/testUI/__init__.py
Labels: frontend

#73 Added splitting of input text by various punctuation
  CogNative/examples/saved_embeds/C
  CogNative/main.py
  CogNative/models/RTVC/RTVC.py
Labels: enhancement, software, ML/AI

#71 Language auto-detection
  CogNative/backend/README.md
  CogNative/backend/backend.py
  CogNative/backend/modules/STT.py
  CogNative/backend/modules/languages.py
  CogNative/main.py
  tests/backend/modules/test_STT.py
Labels: bug, ML/AI

#74 Removed unnecessary RTVC files
  CogNative/models/RTVC/demo_cli.py
  CogNative/models/RTVC/demo_output_00.wav
  CogNative/models/RTVC/demo_toolbox.py
  CogNative/models/RTVC/encoder_preprocess.py
  CogNative/models/RTVC/encoder_train.py
  CogNative/models/RTVC/samples/1320_00000.mp3
  CogNative/models/RTVC/samples/3575_00000.mp3
  CogNative/models/RTVC/samples/6829_00000.mp3
  CogNative/models/RTVC/samples/8230_00000.mp3
  CogNative/models/RTVC/samples/README.md
  CogNative/models/RTVC/samples/VCTK.txt
  CogNative/models/RTVC/samples/p240_00000.mp3
  CogNative/models/RTVC/samples/p260_00000.mp3
  CogNative/models/RTVC/synthesizer_preprocess_audio.py
  CogNative/models/RTVC/synthesizer_preprocess_embeds.py
  CogNative/models/RTVC/synthesizer_train.py
  CogNative/models/RTVC/toolbox/__init__.py
  CogNative/models/RTVC/toolbox/ui.py
  CogNative/models/RTVC/toolbox/utterance.py
  CogNative/models/RTVC/vocoder_preprocess.py
  CogNative/models/RTVC/vocoder_train.py
Labels: ML/AI

#78 Added language auto-detection for voice being cloned
  CogNative/backend/modules/STT.py
  CogNative/backend/modules/languages.py
  CogNative/main.py
Labels: enhancement, software

#80 Added saved_models path
  .gitignore
  CogNative/models/RTVC/saved_models/default/README.md
Labels: bug, critical

#84 Austin - Added helpmsg, updated main readme with UI
  CogNative/main.py
  README.md
  cmdTestAudio.bat
  cmdTestText.bat
Labels: documentation, frontend

#79 Added basic functionality to UI
  CogNative/examples/saved_embeds/C
  CogNative/examples/saved_embeds/examples;BillMaher22.wav.ckpt
  CogNative/examples/saved_embeds/examples;DavidHowell15.wav.ckpt
  CogNative/examples/saved_embeds/examples;TCOC40.wav.ckpt
  CogNative/models/RTVC/RTVC.py
  CogNative/testUI/UI.py
Labels: enhancement, frontend

#85 Create mp3-to-wav.py
  CogNative/backend/modules/utils.py
  CogNative/main.py
Labels: enhancement, software

#91 Austin contextmenu AutoTranslate Script
  AutoTranslate with CogNative.bat
  README.md
Labels: enhancement, frontend

#92 Added support for translation of large text inputs
  CogNative/backend/backend.py
  CogNative/backend/modules/translation.py
  CogNative/backend/modules/utils.py
  CogNative/main.py
Labels: enhancement, software, ML/AI

#96 Fix punctuation splitting
  CogNative/backend/modules/utils.py
Labels: bug, critical

#98 Added punctuation_spacer in utils.py; Integrated into main.py
  CogNative/backend/modules/utils.py
  CogNative/main.py
Labels: bug
